; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = bumperbot_esp32_controller

[env]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
platform_packages = toolchain-xtensa-esp32s3@12.2.0+20230208
build_unflags = -std=gnu++11
build_flags = -std=gnu++20
lib_deps = dlloydev/QuickPID@^3.1.9

monitor_speed = 115200

[env:bumperbot_esp32_controller]
build_src_filter = +<*.cpp>

[env:diagnostic_diff_drive_rotation]
build_src_filter = +<diagnostic/diff_drive_rotation/*.cpp>

[env:diagnostic_feedforward_calibration]
build_src_filter = +<diagnostic/feedforward_calibration/*.cpp>

[env:diagnostic_imu]
build_src_filter = +<diagnostic/imu/*.cpp>
